
logo: ./logo.png
description: > 
  Invention Factory is an intensive summer program for Cooper Union 
  undergraduate engineering students. In 2015, we presented the prototype of our
  design of a universal screwsriver nammed Push and Twist. Our design won second place of 
  that year's invention factory and recived a $3000 cash reward.
  <a href='https://raymondminglee.github.io/'> 
  Back to homepage</a>

theme: jekyll-theme-minimal